### ISSUE TITLE
[Suzu] Failed startup Device after few reboots (Device failed verification)

### ISSUE THREAD

**Issue by lubik1** [RiseOS/bug_tracker#24]
**Device:** Suzu
**Kernel version:** 4.9.138
**Android version:** 9

**Description:**
After few reboots your system failed to startup (few times)

**How to reproduce:**
Just reboot it few times

**Logs:**
![fail](https://user-images.githubusercontent.com/19878552/49339781-6274e280-f63f-11e8-85ae-4717f9c16402.jpeg)

**Comment by Gray47Maxx** [comment]
Confirmed. Also happens on Omni 9 and AOSP.

**Comment by danielgusvt** [comment]
Fixed by https://github.com/sonyxperiadev/kernel/pull/1855?

**Comment by bartcubbins** [comment]
the true reason has not been fixed, reboots remain, only restart reason was fixed

**Comment by bartcubbins** [comment]
this issue still persist <s>and it caused by
https://github.com/bartcubbins/kernel_loire/commit/5a97f442572a7e8a4ecfaf81b0d39a1eb077ddc7</s>

**Comment by bartcubbins** [comment]
fixed
https://github.com/bartcubbins/kernel_loire/commit/0747284a9a57dcec1b414df4fc46714451a085b4
